project = atlys
vendor = xilinx
family = spartan6
part = xc6slx45-2csg324
top_module = small1soc

vfiles = ../../rtl/core.v ../../rtl/cpu.v ../../rtl/stack.v  ../../rtl/icache.v ../../rtl/3rdparty/arbiter.v ../logipi/top.v spi.v ../../rtl/3rdparty/fifo.v ./3rdparty/uart.v ./3rdparty/uart_tx.v ./3rdparty/uart_rx.v
hfiles =

include ../logipi/xilinx.mk
