project = soc
vendor = xilinx
family = spartan6
part = xc6slx9-2-tqg144
top_module = small1soc

vfiles = ../../rtl/core.v ../../rtl/cpu.v ../../rtl/stack.v  ../../rtl/icache.v ../../rtl/3rdparty/arbiter.v top.v spi.v ../../rtl/3rdparty/fifo.v ../../rtl/3rdparty/vgafifo.v ../../rtl/vgatop.v ../../rtl/vga640x480.v
hfiles = ./3rdparty/SDRAM_Controller.vhd

include xilinx.mk
