# TCL File Generated by Component Editor 16.0
# Fri Dec 16 14:15:52 CST 2016
# DO NOT MODIFY


# 
# hps_reset_manager "hps_reset_manager" v1.0
#  2016.12.16.14:15:52
# 
# 

# 
# request TCL package from ACDS 16.0
# 
package require -exact qsys 16.0


# 
# module hps_reset_manager
# 
set_module_property DESCRIPTION ""
set_module_property NAME hps_reset_manager
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP TERASIC
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME hps_reset_manager
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL hps_reset_manager
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file altera_edge_detector.v VERILOG PATH altera_edge_detector.v
add_fileset_file hps_reset.v VERILOG PATH hps_reset.v
add_fileset_file hps_reset_manager.v VERILOG PATH hps_reset_manager.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point hps_cold_reset
# 
add_interface hps_cold_reset reset start
set_interface_property hps_cold_reset associatedClock clock
set_interface_property hps_cold_reset associatedDirectReset ""
set_interface_property hps_cold_reset associatedResetSinks hps_fpga_reset
set_interface_property hps_cold_reset synchronousEdges DEASSERT
set_interface_property hps_cold_reset ENABLED true
set_interface_property hps_cold_reset EXPORT_OF ""
set_interface_property hps_cold_reset PORT_NAME_MAP ""
set_interface_property hps_cold_reset CMSIS_SVD_VARIABLES ""
set_interface_property hps_cold_reset SVD_ADDRESS_GROUP ""

add_interface_port hps_cold_reset hps_cold_reset reset Output 1


# 
# connection point hps_fpga_reset
# 
add_interface hps_fpga_reset reset end
set_interface_property hps_fpga_reset associatedClock clock
set_interface_property hps_fpga_reset synchronousEdges DEASSERT
set_interface_property hps_fpga_reset ENABLED true
set_interface_property hps_fpga_reset EXPORT_OF ""
set_interface_property hps_fpga_reset PORT_NAME_MAP ""
set_interface_property hps_fpga_reset CMSIS_SVD_VARIABLES ""
set_interface_property hps_fpga_reset SVD_ADDRESS_GROUP ""

add_interface_port hps_fpga_reset hps_fpga_reset_n reset_n Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock_clk clk Input 1


# 
# connection point hps_warm_reset
# 
add_interface hps_warm_reset reset start
set_interface_property hps_warm_reset associatedClock clock
set_interface_property hps_warm_reset associatedDirectReset ""
set_interface_property hps_warm_reset associatedResetSinks hps_fpga_reset
set_interface_property hps_warm_reset synchronousEdges DEASSERT
set_interface_property hps_warm_reset ENABLED true
set_interface_property hps_warm_reset EXPORT_OF ""
set_interface_property hps_warm_reset PORT_NAME_MAP ""
set_interface_property hps_warm_reset CMSIS_SVD_VARIABLES ""
set_interface_property hps_warm_reset SVD_ADDRESS_GROUP ""

add_interface_port hps_warm_reset hps_warm_reset reset Output 1

